---
# Source: draw.io/templates/network.yaml
apiVersion: v1
kind: Service
metadata:
  name: drawio
  namespace: default
  labels:
    app: draw.io
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
  - name: http
    port: 8080
  selector:
    app: draw.io
...
---
# Source: draw.io/templates/deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawio
  namespace: default
  labels:
    app: draw.io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: draw.io
    template:
      metadata:
        labels:
          app: draw.io
      spec:
        containers:
        - name: drawio
          image: docker.io/jgraph/drawio:26.0.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 8443
            name: https
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
...
---
# Source: draw.io/templates/network.yaml
apiVersion: networking.k8s/io/v1
kind: Ingress
metadata:
  name: drawio
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  inrgessClassName: nginx
  rules:
  - host: drawio.example.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drawio
            port:
              name: http
...
